/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.slc.sli.headerfooter.service.base;

import com.liferay.counter.service.CounterLocalService;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.search.Indexer;
import com.liferay.portal.kernel.search.IndexerRegistryUtil;
import com.liferay.portal.kernel.search.SearchException;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.model.PersistedModel;
import com.liferay.portal.service.PersistedModelLocalServiceRegistryUtil;
import com.liferay.portal.service.ResourceLocalService;
import com.liferay.portal.service.ResourceService;
import com.liferay.portal.service.UserLocalService;
import com.liferay.portal.service.UserService;
import com.liferay.portal.service.persistence.ResourcePersistence;
import com.liferay.portal.service.persistence.UserPersistence;

import org.slc.sli.headerfooter.model.HeaderFooter;
import org.slc.sli.headerfooter.service.HeaderFooterLocalService;
import org.slc.sli.headerfooter.service.HeaderFooterService;
import org.slc.sli.headerfooter.service.persistence.HeaderFooterPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * The base implementation of the header footer local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link org.slc.sli.headerfooter.service.impl.HeaderFooterLocalServiceImpl}.
 * </p>
 *
 * @author manoj
 * @see org.slc.sli.headerfooter.service.impl.HeaderFooterLocalServiceImpl
 * @see org.slc.sli.headerfooter.service.HeaderFooterLocalServiceUtil
 * @generated
 */
public abstract class HeaderFooterLocalServiceBaseImpl
	implements HeaderFooterLocalService, IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link org.slc.sli.headerfooter.service.HeaderFooterLocalServiceUtil} to access the header footer local service.
	 */

	/**
	 * Adds the header footer to the database. Also notifies the appropriate model listeners.
	 *
	 * @param headerFooter the header footer
	 * @return the header footer that was added
	 * @throws SystemException if a system exception occurred
	 */
	public HeaderFooter addHeaderFooter(HeaderFooter headerFooter)
		throws SystemException {
		headerFooter.setNew(true);

		headerFooter = headerFooterPersistence.update(headerFooter, false);

		Indexer indexer = IndexerRegistryUtil.getIndexer(getModelClassName());

		if (indexer != null) {
			try {
				indexer.reindex(headerFooter);
			}
			catch (SearchException se) {
				if (_log.isWarnEnabled()) {
					_log.warn(se, se);
				}
			}
		}

		return headerFooter;
	}

	/**
	 * Creates a new header footer with the primary key. Does not add the header footer to the database.
	 *
	 * @param id the primary key for the new header footer
	 * @return the new header footer
	 */
	public HeaderFooter createHeaderFooter(long id) {
		return headerFooterPersistence.create(id);
	}

	/**
	 * Deletes the header footer with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param id the primary key of the header footer
	 * @throws PortalException if a header footer with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public void deleteHeaderFooter(long id)
		throws PortalException, SystemException {
		HeaderFooter headerFooter = headerFooterPersistence.remove(id);

		Indexer indexer = IndexerRegistryUtil.getIndexer(getModelClassName());

		if (indexer != null) {
			try {
				indexer.delete(headerFooter);
			}
			catch (SearchException se) {
				if (_log.isWarnEnabled()) {
					_log.warn(se, se);
				}
			}
		}
	}

	/**
	 * Deletes the header footer from the database. Also notifies the appropriate model listeners.
	 *
	 * @param headerFooter the header footer
	 * @throws SystemException if a system exception occurred
	 */
	public void deleteHeaderFooter(HeaderFooter headerFooter)
		throws SystemException {
		headerFooterPersistence.remove(headerFooter);

		Indexer indexer = IndexerRegistryUtil.getIndexer(getModelClassName());

		if (indexer != null) {
			try {
				indexer.delete(headerFooter);
			}
			catch (SearchException se) {
				if (_log.isWarnEnabled()) {
					_log.warn(se, se);
				}
			}
		}
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery)
		throws SystemException {
		return headerFooterPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
		throws SystemException {
		return headerFooterPersistence.findWithDynamicQuery(dynamicQuery,
			start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator orderByComparator) throws SystemException {
		return headerFooterPersistence.findWithDynamicQuery(dynamicQuery,
			start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	public long dynamicQueryCount(DynamicQuery dynamicQuery)
		throws SystemException {
		return headerFooterPersistence.countWithDynamicQuery(dynamicQuery);
	}

	public HeaderFooter fetchHeaderFooter(long id) throws SystemException {
		return headerFooterPersistence.fetchByPrimaryKey(id);
	}

	/**
	 * Returns the header footer with the primary key.
	 *
	 * @param id the primary key of the header footer
	 * @return the header footer
	 * @throws PortalException if a header footer with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public HeaderFooter getHeaderFooter(long id)
		throws PortalException, SystemException {
		return headerFooterPersistence.findByPrimaryKey(id);
	}

	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException, SystemException {
		return headerFooterPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the header footers.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param start the lower bound of the range of header footers
	 * @param end the upper bound of the range of header footers (not inclusive)
	 * @return the range of header footers
	 * @throws SystemException if a system exception occurred
	 */
	public List<HeaderFooter> getHeaderFooters(int start, int end)
		throws SystemException {
		return headerFooterPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of header footers.
	 *
	 * @return the number of header footers
	 * @throws SystemException if a system exception occurred
	 */
	public int getHeaderFootersCount() throws SystemException {
		return headerFooterPersistence.countAll();
	}

	/**
	 * Updates the header footer in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param headerFooter the header footer
	 * @return the header footer that was updated
	 * @throws SystemException if a system exception occurred
	 */
	public HeaderFooter updateHeaderFooter(HeaderFooter headerFooter)
		throws SystemException {
		return updateHeaderFooter(headerFooter, true);
	}

	/**
	 * Updates the header footer in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param headerFooter the header footer
	 * @param merge whether to merge the header footer with the current session. See {@link com.liferay.portal.service.persistence.BatchSession#update(com.liferay.portal.kernel.dao.orm.Session, com.liferay.portal.model.BaseModel, boolean)} for an explanation.
	 * @return the header footer that was updated
	 * @throws SystemException if a system exception occurred
	 */
	public HeaderFooter updateHeaderFooter(HeaderFooter headerFooter,
		boolean merge) throws SystemException {
		headerFooter.setNew(false);

		headerFooter = headerFooterPersistence.update(headerFooter, merge);

		Indexer indexer = IndexerRegistryUtil.getIndexer(getModelClassName());

		if (indexer != null) {
			try {
				indexer.reindex(headerFooter);
			}
			catch (SearchException se) {
				if (_log.isWarnEnabled()) {
					_log.warn(se, se);
				}
			}
		}

		return headerFooter;
	}

	/**
	 * Returns the header footer local service.
	 *
	 * @return the header footer local service
	 */
	public HeaderFooterLocalService getHeaderFooterLocalService() {
		return headerFooterLocalService;
	}

	/**
	 * Sets the header footer local service.
	 *
	 * @param headerFooterLocalService the header footer local service
	 */
	public void setHeaderFooterLocalService(
		HeaderFooterLocalService headerFooterLocalService) {
		this.headerFooterLocalService = headerFooterLocalService;
	}

	/**
	 * Returns the header footer remote service.
	 *
	 * @return the header footer remote service
	 */
	public HeaderFooterService getHeaderFooterService() {
		return headerFooterService;
	}

	/**
	 * Sets the header footer remote service.
	 *
	 * @param headerFooterService the header footer remote service
	 */
	public void setHeaderFooterService(HeaderFooterService headerFooterService) {
		this.headerFooterService = headerFooterService;
	}

	/**
	 * Returns the header footer persistence.
	 *
	 * @return the header footer persistence
	 */
	public HeaderFooterPersistence getHeaderFooterPersistence() {
		return headerFooterPersistence;
	}

	/**
	 * Sets the header footer persistence.
	 *
	 * @param headerFooterPersistence the header footer persistence
	 */
	public void setHeaderFooterPersistence(
		HeaderFooterPersistence headerFooterPersistence) {
		this.headerFooterPersistence = headerFooterPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the resource remote service.
	 *
	 * @return the resource remote service
	 */
	public ResourceService getResourceService() {
		return resourceService;
	}

	/**
	 * Sets the resource remote service.
	 *
	 * @param resourceService the resource remote service
	 */
	public void setResourceService(ResourceService resourceService) {
		this.resourceService = resourceService;
	}

	/**
	 * Returns the resource persistence.
	 *
	 * @return the resource persistence
	 */
	public ResourcePersistence getResourcePersistence() {
		return resourcePersistence;
	}

	/**
	 * Sets the resource persistence.
	 *
	 * @param resourcePersistence the resource persistence
	 */
	public void setResourcePersistence(ResourcePersistence resourcePersistence) {
		this.resourcePersistence = resourcePersistence;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		PersistedModelLocalServiceRegistryUtil.register("org.slc.sli.headerfooter.model.HeaderFooter",
			headerFooterLocalService);
	}

	public void destroy() {
		PersistedModelLocalServiceRegistryUtil.unregister(
			"org.slc.sli.headerfooter.model.HeaderFooter");
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	protected Class<?> getModelClass() {
		return HeaderFooter.class;
	}

	protected String getModelClassName() {
		return HeaderFooter.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = headerFooterPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = HeaderFooterLocalService.class)
	protected HeaderFooterLocalService headerFooterLocalService;
	@BeanReference(type = HeaderFooterService.class)
	protected HeaderFooterService headerFooterService;
	@BeanReference(type = HeaderFooterPersistence.class)
	protected HeaderFooterPersistence headerFooterPersistence;
	@BeanReference(type = CounterLocalService.class)
	protected CounterLocalService counterLocalService;
	@BeanReference(type = ResourceLocalService.class)
	protected ResourceLocalService resourceLocalService;
	@BeanReference(type = ResourceService.class)
	protected ResourceService resourceService;
	@BeanReference(type = ResourcePersistence.class)
	protected ResourcePersistence resourcePersistence;
	@BeanReference(type = UserLocalService.class)
	protected UserLocalService userLocalService;
	@BeanReference(type = UserService.class)
	protected UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private static Log _log = LogFactoryUtil.getLog(HeaderFooterLocalServiceBaseImpl.class);
	private String _beanIdentifier;
}